# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# AR5RASTER.py
# Generated by Frank Hanssen, 25.09.2017
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

#Check available license
if arcpy.CheckExtension("Spatial") == "Available":
        arcpy.CheckOutExtension("Spatial")

#Overwrite existing outputs
arcpy.env.overwriteOutput = True

# Local variables:
AR5_2017_NORWAY_ROI_shp = "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\AR5_2017_NORWAY_ROI.shp"
ARTYPE = Raster("D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARTYPE.TIF")
ARTRESLAG = Raster("D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARTRESLAG.TIF")
ARSKOGBON = Raster("D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARSKOGBON.TIF")
ARGRUNNF = Raster("D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARGRUNNF.TIF")

# Set Geoprocessing environments
arcpy.env.workspace = "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\Processing"
arcpy.env.scratchWorkspace = "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\Processing\\Temp"
arcpy.env.snapRaster = "D:\\Arbeid\\IMAGINE\\Rawdata\\DEM10\DEM10.TIF"
arcpy.env.extent = "550180.001242988 7002531.65012117 588459.629998862 7044009.99571779"
arcpy.env.cellSize = "10"
arcpy.env.mask = "D:\\Arbeid\\IMAGINE\\Rawdata\\ROI_NO.shp"

# Process: Feature to Raster
#arcpy.FeatureToRaster_conversion(AR5_2017_NORWAY_ROI_shp, "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARTYPE.TIF", ARTYPE, "10")
#arcpy.FeatureToRaster_conversion(AR5_2017_NORWAY_ROI_shp, "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARTRESLAG.TIF", ARTRESLAG, "10")
#arcpy.FeatureToRaster_conversion(AR5_2017_NORWAY_ROI_shp, "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARSKOGBON.TIF", ARSKOGBON, "10")
#arcpy.FeatureToRaster_conversion(AR5_2017_NORWAY_ROI_shp, "D:\\Arbeid\\IMAGINE\\Rawdata\\AR5\\ARGRUNNF.TIF", ARGRUNNF, "10")

# Process: Map algebra
AR5_1=Con((ARTYPE == 21) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 1, 0)
AR5_1.save("AR5_1.TIF")

AR5_2=Con((ARTYPE == 21) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 2, 0)
AR5_2.save("AR5_2.TIF")

AR5_3=Con((ARTYPE == 22) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 3, 0)
AR5_3.save("AR5_3.TIF")

AR5_4=Con((ARTYPE == 22) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 43), 4, 0)
AR5_4.save("AR5_4.TIF")

AR5_5=Con((ARTYPE == 22) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 5, 0)
AR5_5.save("AR5_5.TIF")

AR5_6=Con((ARTYPE == 23) & (ARTRESLAG == 31) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 6, 0)
AR5_6.save("AR5_6.TIF")

AR5_7=Con((ARTYPE == 23) & (ARTRESLAG == 31) & (ARSKOGBON == 98) & (ARGRUNNF == 43), 7, 0)
AR5_7.save("AR5_7.TIF")

AR5_8=Con((ARTYPE == 23) & (ARTRESLAG == 31) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 8, 0)
AR5_8.save("AR5_8.TIF")

AR5_9=Con((ARTYPE == 23) & (ARTRESLAG == 32) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 9, 0)
AR5_9.save("AR5_9.TIF")

AR5_10=Con((ARTYPE == 23) & (ARTRESLAG == 32) & (ARSKOGBON == 98) & (ARGRUNNF == 43), 10, 0)
AR5_10.save("AR5_10.TIF")

AR5_11=Con((ARTYPE == 23) & (ARTRESLAG == 32) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 11, 0)
AR5_11.save("AR5_11.TIF")

AR5_12=Con((ARTYPE == 23) & (ARTRESLAG == 33) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 12, 0)
AR5_12.save("AR5_12.TIF")

AR5_13=Con((ARTYPE == 23) & (ARTRESLAG == 33) & (ARSKOGBON == 98) & (ARGRUNNF == 43), 13, 0)
AR5_13.save("AR5_13.TIF")

AR5_14=Con((ARTYPE == 23) & (ARTRESLAG == 33) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 14, 0)
AR5_14.save("AR5_14.TIF")

AR5_15=Con((ARTYPE == 23) & (ARTRESLAG == 39) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 15, 0)
AR5_15.save("AR5_15.TIF")

AR5_16=Con((ARTYPE == 23) & (ARTRESLAG == 39) & (ARSKOGBON == 98) & (ARGRUNNF == 43), 16, 0)
AR5_16.save("AR5_16.TIF")

AR5_17=Con((ARTYPE == 23) & (ARTRESLAG == 39) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 17, 0)
AR5_17.save("AR5_17.TIF")

AR5_18=Con((ARTYPE == 23) & (ARTRESLAG == 99) & (ARSKOGBON == 98) & (ARGRUNNF == 43), 18, 0)
AR5_18.save("AR5_18.TIF")

AR5_19=Con((ARTYPE == 23) & (ARTRESLAG == 99) & (ARSKOGBON == 98) & (ARGRUNNF == 44), 19, 0)
AR5_19.save("AR5_19.TIF")

AR5_20=Con((ARTYPE == 23) & (ARTRESLAG == 99) & (ARSKOGBON == 98) & (ARGRUNNF == 45), 20, 0)
AR5_20.save("AR5_20.TIF")

AR5_21=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 15) & (ARGRUNNF == 44), 21, 0)
AR5_21.save("AR5_21.TIF")

AR5_22=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 15) & (ARGRUNNF == 45), 22, 0)
AR5_22.save("AR5_22.TIF")

AR5_23=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 15) & (ARGRUNNF == 44), 23, 0)
AR5_23.save("AR5_23.TIF")

AR5_24=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 15) & (ARGRUNNF == 45), 24, 0)
AR5_24.save("AR5_24.TIF")

AR5_25=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 15) & (ARGRUNNF == 44), 25, 0)
AR5_25.save("AR5_25.TIF")

AR5_26=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 15) & (ARGRUNNF == 45), 26, 0)
AR5_26.save("AR5_26.TIF")

AR5_27=Con((ARTYPE == 60) & (ARTRESLAG == 31) & (ARSKOGBON == 15) & (ARGRUNNF == 45), 27, 0)
AR5_27.save("AR5_27.TIF")

AR5_28=Con((ARTYPE == 60) & (ARTRESLAG == 32) & (ARSKOGBON == 15) & (ARGRUNNF == 45), 28, 0)
AR5_28.save("AR5_28.TIF")

AR5_29=Con((ARTYPE == 60) & (ARTRESLAG == 33) & (ARSKOGBON == 15) & (ARGRUNNF == 45), 29, 0)
AR5_29.save("AR5_29.TIF")

AR5_30=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 14) & (ARGRUNNF == 43), 30, 0)
AR5_30.save("AR5_30.TIF")

AR5_31=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 14) & (ARGRUNNF == 44), 31, 0)
AR5_31.save("AR5_31.TIF")

AR5_32=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 14) & (ARGRUNNF == 45), 32, 0)
AR5_32.save("AR5_32.TIF")

AR5_33=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 14) & (ARGRUNNF == 43), 33, 0)
AR5_33.save("AR5_33.TIF")

AR5_34=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 14) & (ARGRUNNF == 44), 34, 0)
AR5_34.save("AR5_34.TIF")

AR5_35=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 14) & (ARGRUNNF == 45), 35, 0)
AR5_35.save("AR5_35.TIF")

AR5_36=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 14) & (ARGRUNNF == 43), 36, 0)
AR5_36.save("AR5_36.TIF")

AR5_37=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 14) & (ARGRUNNF == 44), 37, 0)
AR5_37.save("AR5_37.TIF")

AR5_38=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 14) & (ARGRUNNF == 45), 38, 0)
AR5_38.save("AR5_38.TIF")

AR5_39=Con((ARTYPE == 60) & (ARTRESLAG == 31) & (ARSKOGBON == 14) & (ARGRUNNF == 45), 39, 0)
AR5_39.save("AR5_39.TIF")

AR5_40=Con((ARTYPE == 60) & (ARTRESLAG == 32) & (ARSKOGBON == 14) & (ARGRUNNF == 45), 40, 0)
AR5_40.save("AR5_40.TIF")

AR5_41=Con((ARTYPE == 60) & (ARTRESLAG == 33) & (ARSKOGBON == 14) & (ARGRUNNF == 45), 41, 0)
AR5_41.save("AR5_41.TIF")

AR5_42=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 13) & (ARGRUNNF == 41), 42, 0)
AR5_42.save("AR5_42.TIF")

AR5_43=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 13) & (ARGRUNNF == 43), 43, 0)
AR5_43.save("AR5_43.TIF")

AR5_44=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 13) & (ARGRUNNF == 44), 44, 0)
AR5_44.save("AR5_44.TIF")

AR5_45=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 13) & (ARGRUNNF == 45), 45, 0)
AR5_45.save("AR5_45.TIF")

AR5_46=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 13) & (ARGRUNNF == 41), 46, 0)
AR5_46.save("AR5_46.TIF")

AR5_47=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 13) & (ARGRUNNF == 43), 47, 0)
AR5_47.save("AR5_47.TIF")

AR5_48=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 13) & (ARGRUNNF == 44), 48, 0)
AR5_48.save("AR5_48.TIF")

AR5_49=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 13) & (ARGRUNNF == 45), 49, 0)
AR5_49.save("AR5_49.TIF")

AR5_50=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 13) & (ARGRUNNF == 41), 50, 0)
AR5_50.save("AR5_50.TIF")

AR5_51=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 13) & (ARGRUNNF == 43), 51, 0)
AR5_51.save("AR5_51.TIF")

AR5_52=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 13) & (ARGRUNNF == 44), 52, 0)
AR5_52.save("AR5_52.TIF")

AR5_53=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 13) & (ARGRUNNF == 45), 53, 0)
AR5_53.save("AR5_53.TIF")

AR5_54=Con((ARTYPE == 60) & (ARTRESLAG == 31) & (ARSKOGBON == 13) & (ARGRUNNF == 45), 54, 0)
AR5_54.save("AR5_54.TIF")

AR5_55=Con((ARTYPE == 60) & (ARTRESLAG == 32) & (ARSKOGBON == 13) & (ARGRUNNF == 45), 55, 0)
AR5_55.save("AR5_55.TIF")

AR5_56=Con((ARTYPE == 60) & (ARTRESLAG == 33) & (ARSKOGBON == 13) & (ARGRUNNF == 45), 56, 0)
AR5_56.save("AR5_56.TIF")

AR5_57=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 12) & (ARGRUNNF == 41), 57, 0)
AR5_57.save("AR5_57.TIF")

AR5_58=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 12) & (ARGRUNNF == 43), 58, 0)
AR5_58.save("AR5_58.TIF")

AR5_59=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 12) & (ARGRUNNF == 44), 59, 0)
AR5_59.save("AR5_59.TIF")

AR5_60=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 12) & (ARGRUNNF == 45), 60, 0)
AR5_60.save("AR5_60.TIF")
           
AR5_61=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 12) & (ARGRUNNF == 41), 61, 0)
AR5_61.save("AR5_61.TIF")
           
AR5_62=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 12) & (ARGRUNNF == 43), 62, 0)
AR5_62.save("AR5_62.TIF")

AR5_63=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 12) & (ARGRUNNF == 44), 63, 0)
AR5_63.save("AR5_63.TIF")

AR5_64=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 12) & (ARGRUNNF == 45), 64, 0)
AR5_64.save("AR5_64.TIF")

AR5_65=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 12) & (ARGRUNNF == 41), 65, 0)
AR5_65.save("AR5_65.TIF")

AR5_66=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 12) & (ARGRUNNF == 43), 66, 0)
AR5_66.save("AR5_66.TIF")

AR5_67=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 12) & (ARGRUNNF == 44), 67, 0)
AR5_67.save("AR5_67.TIF")

AR5_68=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 12) & (ARGRUNNF == 45), 68, 0)
AR5_68.save("AR5_68.TIF")

AR5_69=Con((ARTYPE == 60) & (ARTRESLAG == 31) & (ARSKOGBON == 12) & (ARGRUNNF == 45), 69, 0)
AR5_69.save("AR5_69.TIF")

AR5_70=Con((ARTYPE == 60) & (ARTRESLAG == 33) & (ARSKOGBON == 12) & (ARGRUNNF == 45), 70, 0)
AR5_70.save("AR5_70.TIF")

AR5_71=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 11) & (ARGRUNNF == 41), 71, 0)
AR5_71.save("AR5_71.TIF")

AR5_72=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 11) & (ARGRUNNF == 42), 72, 0)
AR5_72.save("AR5_72.TIF")

AR5_73=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 11) & (ARGRUNNF == 43), 73, 0)
AR5_73.save("AR5_73.TIF")

AR5_74=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 11) & (ARGRUNNF == 44), 74, 0)
AR5_74.save("AR5_74.TIF")

AR5_75=Con((ARTYPE == 30) & (ARTRESLAG == 31) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 75, 0)
AR5_75.save("AR5_75.TIF")
           
AR5_76=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 11) & (ARGRUNNF == 41), 76, 0)
AR5_76.save("AR5_76.TIF")

AR5_77=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 11) & (ARGRUNNF == 42), 77, 0)
AR5_77.save("AR5_77.TIF")

AR5_78=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 11) & (ARGRUNNF == 43), 78, 0)
AR5_78.save("AR5_78.TIF")

AR5_79=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 11) & (ARGRUNNF == 44), 79, 0)
AR5_79.save("AR5_79.TIF")

AR5_80=Con((ARTYPE == 30) & (ARTRESLAG == 32) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 80, 0)
AR5_80.save("AR5_80.TIF")

AR5_81=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 11) & (ARGRUNNF == 41), 81, 0)
AR5_81.save("AR5_81.TIF")

AR5_82=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 11) & (ARGRUNNF == 42), 82, 0)
AR5_82.save("AR5_82.TIF")

AR5_83=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 11) & (ARGRUNNF == 43), 83, 0)
AR5_83.save("AR5_83.TIF")

AR5_84=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 11) & (ARGRUNNF == 44), 84, 0)
AR5_84.save("AR5_84.TIF")

AR5_85=Con((ARTYPE == 30) & (ARTRESLAG == 33) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 85, 0)
AR5_85.save("AR5_85.TIF")

AR5_86=Con((ARTYPE == 60) & (ARTRESLAG == 32) & (ARSKOGBON == 12) & (ARGRUNNF == 45), 86, 0)
AR5_86.save("AR5_86.TIF")

AR5_87=Con((ARTYPE == 60) & (ARTRESLAG == 31) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 87, 0)
AR5_87.save("AR5_87.TIF")

AR5_88=Con((ARTYPE == 60) & (ARTRESLAG == 32) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 88, 0)
AR5_88.save("AR5_88.TIF")

AR5_89=Con((ARTYPE == 60) & (ARTRESLAG == 33) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 89, 0)
AR5_89.save("AR5_89.TIF")

AR5_90=Con((ARTYPE == 60) & (ARTRESLAG == 39) & (ARSKOGBON == 11) & (ARGRUNNF == 45), 90, 0)
AR5_90.save("AR5_90.TIF")

AR5_91=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 15) & (ARGRUNNF == 44), 91, 0)
AR5_91.save("AR5_91.TIF")

AR5_92=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 14) & (ARGRUNNF == 44), 92, 0)
AR5_92.save("AR5_92.TIF")

AR5_93=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 13) & (ARGRUNNF == 44), 93, 0)
AR5_93.save("AR5_93.TIF")

AR5_94=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 11) & (ARGRUNNF == 44), 94, 0)
AR5_94.save("AR5_94.TIF")

AR5_95=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 14) & (ARGRUNNF == 43), 95, 0)
AR5_95.save("AR5_95.TIF")

AR5_96=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 13) & (ARGRUNNF == 43), 96, 0)
AR5_96.save("AR5_96.TIF")

AR5_97=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 11) & (ARGRUNNF == 41), 97, 0)
AR5_97.save("AR5_97.TIF")

AR5_98=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 11) & (ARGRUNNF == 42), 98, 0)
AR5_98.save("AR5_98.TIF")
           
AR5_99=Con((ARTYPE == 50) & (ARTRESLAG == 39) & (ARSKOGBON == 11) & (ARGRUNNF == 43), 99, 0)
AR5_99.save("AR5_99.TIF")

AR5_100=Con((ARTYPE == 11) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 98), 100, 0)
AR5_100.save("AR5_100.TIF")

AR5_101=Con((ARTYPE == 12) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 98), 101, 0)
AR5_101.save("AR5_101.TIF")

AR5_102=Con((ARTYPE == 70) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 98), 102, 0)
AR5_102.save("AR5_102.TIF")

AR5_103=Con((ARTYPE == 80) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 98), 103, 0)
AR5_103.save("AR5_103.TIF")

AR5_104=Con((ARTYPE == 99) & (ARTRESLAG == 98) & (ARSKOGBON == 98) & (ARGRUNNF == 98), 104, 0)
AR5_104.save("AR5_104.TIF")

#Sum rasters

rasterList  = arcpy.ListRasters("*")
print rasterList

OutCellStatistics = CellStatistics(rasterList, "SUM", "NODATA")
OutCellStatistics.save("D:/Arbeid/IMAGINE/Rawdata/AR5/AR5Raster.tif")
